### ISSUE TITLE
Implement CLI

### ISSUE THREAD

**Issue by ia0** [google/wasefire#38]
- [ ] `wasefire applet-list`
- [x] `wasefire applet-install` (could have an `--update` flag to update if present) #617
- [ ] `wasefire applet-update` (could have an `--install` flag to install if absent)
- [x] `wasefire applet-uninstall` #617
- [ ] `wasefire applet-enable`?
- [ ] `wasefire applet-disable`?
- [x] `wasefire applet-rpc` #517
- [x] `wasefire applet-exit-status` #617
- [x] `wasefire host` #650
- [x] `wasefire platform-list` #516 
- [x] `wasefire platform-info` #652 
- [x] `wasefire platform-update-{metadata,transfer}` #609
- [x] `wasefire platform-reboot` #518
- [x] `wasefire platform-lock` #617
- [x] `wasefire platform-rpc` #519
- [x] `wasefire rust-applet-new` #414 
- [ ] `wasefire rust-applet-check`?
- [x] `wasefire rust-applet-build` #414 
- [x] `wasefire rust-applet-test` #414 
- [ ] `wasefire rust-applet-update`? (builds and calls `applet-update` with the artifact)
- [x] `wasefire rust-applet-install` (builds and calls `applet-install` with the artifact) #675 
- [x] `wasefire completion` #414 
- [x] `wasefire --serial=8efd281a` to choose from `platform-list` #517
- [x] `wasefire self-update` #689

For applet attestation:
- [ ] `wasefire key-init` generates a (possibly passphrase-protected) private key locally.
- [ ] `wasefire key-export` exports the public key (backup of the private key can be done without the CLI from the `~/.wasefire` directory)
- [ ] `wasefire platform-provision` transfers the public key to a blank platform (this can also sign the public key of another CLI and transfer it to a provisioned platform, if a public key is provided)
